# **Gerando Arrays**

In [6]:
import numpy as np

print(np.zeros(10))
print(np.ones(10))
print(np.arange(20+1))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## **Gerando arrays com Métodos Built-in**

In [7]:
print(np.arange(0,10,1))
print(np.arange(0,10,2))
print(np.arange(0,10,3))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]


## **Arrays Aleatórios Unidimensional**



In [9]:
print(np.random.rand(1))
print(np.random.rand(2))
print(np.random.rand(3))

[0.07103191]
[0.99910457 0.56909285]
[0.80323834 0.02231248 0.60902473]


## **Arrays Aleatórios Multidimensional**


In [10]:
#Cria uma matriz
print(np.random.rand(2,2))
print(np.random.rand(2,4))

[[0.08842842 0.22120468]
 [0.70138544 0.7457669 ]]
[[0.89261443 0.64345538 0.44995165 0.38522218]
 [0.6679416  0.89642769 0.661857   0.28248634]]


## Principais Atributos: Max() e Min()

In [11]:
vetor = np.random.rand(3)
print(vetor)
print(vetor.max())
print(vetor.min())

[0.45751372 0.07873973 0.66782715]
0.6678271521420666
0.07873972925803385


## *Principais Atributos: dtype* 

In [12]:
#Pra ver qual tipo de dado do vetor
vetor = np.random.rand(3)
print(vetor.dtype)
vetor = np.arange(3)
print(vetor.dtype)

float64
int64


## *Principais Atributos: Slicing*

In [15]:
vetor = np.arange(1,20,1)
print(vetor)
vetor1 = vetor[1:6]
print(vetor1)
vetor[1:6] = 20
print(vetor)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 3 4 5 6]
[ 1 20 20 20 20 20  7  8  9 10 11 12 13 14 15 16 17 18 19]


## Principais Funções Matemáticas

In [16]:
vetor = np.arange(4)
print(np.exp(vetor))
print(np.sqrt(vetor))

[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]


## Transformando Arquivo em Arrays: genfromtxt


In [24]:
import numpy as np 
from numpy import genfromtxt

#importando arquivos para dentro do colab
data = genfromtxt("arquivos_aula06/array1.txt", delimiter = ",")
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## Transformando Arquivo em Arrays: loadtxt


In [25]:
data = np.loadtxt("arquivos_aula06/array1.txt", dtype = int, delimiter=",")
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
